on:
  pull_request:
  workflow_dispatch:

jobs:
  jobs1:
    runs-on: ubuntu-latest
    # container: debian:bullseye-slim
    services:
        postgres:
          image: postgres:13
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - run: apt-get update
      - run: > 
          apt-get install -y --no-install-recommends
          python3-pytest
          python3-sqlalchemy
          python3-psycopg2
      - uses: actions/checkout@v3
      - run: python3 -m pytest